name: CI

on:
  pull_request:
  merge_group:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.0.1
